[package]
name = "tracing-perfetto-sdk-layer"
description = "Qorix-forked provider of tracing layers for tracing-subscriber using the native C++ Perfetto SDK"
license = "Apache-2.0"
repository = "https://github.com/qorix-group/tracing-perfetto-sdk.git"
version.workspace = true
edition.workspace = true

[dependencies]
bytes.workspace = true
cxx.workspace = true
dashmap.workspace = true
nix = { workspace = true, features = ["time"] }
prost.workspace = true
thiserror.workspace = true
thread-id.workspace = true
thread_local.workspace = true
tracing.workspace = true
tracing-perfetto-sdk-schema.workspace = true
tracing-perfetto-sdk-sys = { workspace = true, optional = true }
tracing-subscriber.workspace = true
libc = { version = "0.2" }
async_runtime = { path = "/tmp/performance_stack_rust/async_runtime" }

[dev-dependencies]
anyhow.workspace = true
serde_yaml.workspace = true
tracing-appender.workspace = true

[features]
default = ["sdk", "tokio"]
tokio = []
serde = ["tracing-perfetto-sdk-schema/serde"]
sdk = ["dep:tracing-perfetto-sdk-sys"]

[[example]]
name = "native-layer"
required-features = ["serde"]

[[example]]
name = "perfetto-dump-trace"
required-features = ["serde"]

[[example]]
name = "sdk-layer"
required-features = ["serde"]

[[test]]
name = "kitchen_sink"
required-features = ["serde"]
